version: '3.7'

services:
  api:
    container_name: facebook-marketplace-scrapper-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
  redis:
    image : redis:7
    container_name: facebook-marketplace-scrapper-redis
    command:
      - "redis-server"
      - "--requirepass ${REDIS_PASSWORD}"
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  postgres:
    container_name: facebook-marketplace-scrapper-postgres
    image: postgres:15
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    container_name: facebook-marketplace-scrapper-rabbitmq
    image: rabbitmq:3.9-management
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - app-network
networks:
  app-network:
volumes:
  pgdata: {}
